### ISSUE TITLE
figlet: command not found

### ISSUE THREAD

**Issue by anbo724** [3xp10it/xwifi#3]
I run this project on MacOS.
And get the error:
/bin/sh: figlet: command not found
use noroot user run `brew install figlet`
Traceback (most recent call last):
  File "xwifi.py", line 23, in <module>
    figlet2file("xwifi", 0, True)
  File "/anaconda3/lib/python3.6/site-packages/exp10it.py", line 1272, in figlet2file
    all_font_name_list = get_all_file_name(figlet_font_dir, ['tlf', 'flf'])
UnboundLocalError: local variable 'figlet_font_dir' referenced before assignment

**Comment by 3xp10it** [comment]
Try to use run the script with root privilege
